from __future__ import annotations

import json
from html import escape


def markdown_report(report: dict) -> str:
    device = report.get("device", {})
    coverage = report.get("metadata_coverage", {})
    risk = report.get("risk", {})
    telephony = report.get("telephony", {})
    graph = report.get("component_graph", {})
    timeline = report.get("install_timeline", [])
    incident_timeline = report.get("incident_timeline", [])
    network = report.get("network", {})
    runtime = report.get("runtime", {})
    signing_packages = [
        item for item in report.get("package_metadata", [])
        if item.get("apk_sha256")
    ]

    lines = [
        "# DroidShield Security Report",
        "",
        f"- Generated: {report.get('generated_at', 'unknown')}",
        f"- Device: {device.get('manufacturer', 'unknown')} {device.get('model', 'unknown')}",
        f"- Android: {device.get('android', 'unknown')} (SDK {device.get('sdk', 'unknown')})",
        f"- Security patch: {device.get('security_patch', 'unknown')}",
        f"- Packages: {coverage.get('packages_total', len(report.get('packages', [])))}",
        f"- Third-party packages: {coverage.get('third_party_total', len(report.get('third_party_packages', [])))}",
        f"- Packages analyzed: {coverage.get('packages_analyzed', len(report.get('package_metadata', [])))}",
        "",
        "## Risk",
        "",
        f"**{risk.get('level', 'unknown')} — {risk.get('score', 0)}/100** "
        f"(confidence: {risk.get('confidence', 'unknown')}; heuristic: {risk.get('heuristic', True)})",
        "",
        "Signals:",
    ]
    lines.extend(f"- {signal}" for signal in risk.get("signals", []))

    lines += ["", "## Active component graph", ""]
    lines.append(
        f"- Nodes: {graph.get('node_count', 0)}; edges: {graph.get('edge_count', 0)}"
    )
    for node in graph.get("nodes", [])[:200]:
        roles = ", ".join(node.get("active_roles", [])) or "none"
        component_count = sum(
            len(node.get("components", {}).get(key, []))
            for key in ("services", "receivers", "providers")
        )
        lines.append(
            f"- {node['package']} — active roles: {roles}; "
            f"declared components: {component_count}"
        )

    lines += ["", "## Install/update timeline", ""]
    if not timeline:
        lines.append("No install/update timestamps were available for the analyzed packages.")
    else:
        for event in timeline[:100]:
            installer = event.get("installer") or "unknown"
            lines.append(
                f"- {event.get('timestamp')} — {event.get('type')} — "
                f"{event.get('package')} — installer: {installer}"
            )

    lines += ["", "## Incident timeline", ""]
    if not incident_timeline:
        lines.append("No incident timeline events were available.")
    else:
        for event in incident_timeline[:150]:
            details = ", ".join(f"{key}={value}" for key, value in event.items() if key not in {"timestamp", "type"})
            lines.append(f"- {event.get('timestamp')} — {event.get('type')} — {details}")

    lines += ["", "## Findings", ""]
    findings = report.get("findings", [])
    if not findings:
        lines.append("No findings were generated by the current rule set.")
    for item in findings:
        package = f" {item.get('package')}" if item.get("package") else ""
        lines.append(
            f"- **{item.get('severity')}** — {item.get('title')}{package}: "
            f"{item.get('description')}"
        )

    lines += ["", "## Package assessment highlights", ""]
    assessments = [
        item for item in report.get("package_assessments", [])
        if item.get("level") in {"HIGH", "MEDIUM"}
    ]
    if not assessments:
        lines.append("No medium/high capability combinations were recorded.")
    else:
        for item in assessments[:100]:
            lines.append(
                f"- {item['package']} — {item['level']} ({item['score']}): "
                f"{', '.join(item.get('signals', [])) or 'no named signals'}"
            )

    lines += ["", "## APK evidence", ""]
    lines.append(
        f"- Packages with collected device APK hashes: {len(signing_packages)}"
    )
    lines.append(
        "- APK signer/certificate details are available in offline APK analysis "
        "when apksigner is installed."
    )

    lines += [
        "",
        "## Runtime and network evidence",
        "",
        f"- Process lines collected: {len(runtime.get('processes', []))}",
        f"- Service lines collected: {len(runtime.get('services', []))}",
        f"- Filtered security log lines: {len(runtime.get('logcat_security', []))}",
        f"- Socket lines collected: {len(network.get('sockets', []))}",
        "",
        "## Telephony",
        "",
        f"- Verification status: {telephony.get('verified', False)}",
        f"- Note: {telephony.get('note', 'No telephony note.')}",
    ]

    lines += ["", "## Hardening", ""]
    lines.extend(f"- {item}" for item in report.get("hardening", []))

    return "\n".join(lines) + "\n"


def html_report(report: dict) -> str:
    data = json.dumps(report, indent=2)
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<title>DroidShield Security Report</title>"
        "<style>body{font-family:system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem}"
        "pre{white-space:pre-wrap;word-break:break-word;background:#f5f5f5;padding:1rem;border-radius:8px}"
        "</style></head><body>"
        "<h1>DroidShield Security Report</h1>"
        "<p>Structured machine-readable evidence is embedded below.</p>"
        f"<pre>{escape(data)}</pre>"
        "</body></html>"
    )
