from __future__ import annotations

import json
from html import escape


def markdown_report(report: dict) -> str:
    device = report.get("device", {})
    coverage = report.get("metadata_coverage", {})
    risk = report.get("risk", {})
    telephony = report.get("telephony", {})

    lines = [
        "# DroidShield Security Report",
        "",
        f"- Generated: {report.get('generated_at', 'unknown')}",
        f"- Device: {device.get('manufacturer', 'unknown')} {device.get('model', 'unknown')}",
        f"- Android: {device.get('android', 'unknown')} (SDK {device.get('sdk', 'unknown')})",
        f"- Security patch: {device.get('security_patch', 'unknown')}",
        f"- Packages: {coverage.get('packages_total', len(report.get('packages', [])))}",
        f"- Third-party packages: {coverage.get('third_party_total', len(report.get('third_party_packages', [])))}",
        f"- Packages analyzed: {coverage.get('packages_analyzed', len(report.get('package_metadata', [])))}",
        "",
        "## Risk",
        "",
        f"**{risk.get('level', 'unknown')} — {risk.get('score', 0)}/100** "
        f"(confidence: {risk.get('confidence', 'unknown')}; heuristic: {risk.get('heuristic', True)})",
        "",
        "Signals:",
    ]
    lines.extend(f"- {signal}" for signal in risk.get("signals", []))

    lines += ["", "## Findings", ""]
    findings = report.get("findings", [])
    if not findings:
        lines.append("No findings were generated by the current rule set.")
    for item in findings:
        package = f" `{item.get('package')}`" if item.get("package") else ""
        lines.append(
            f"- **{item.get('severity')}** — {item.get('title')}{package}: "
            f"{item.get('description')}"
        )

    lines += ["", "## Package assessment highlights", ""]
    assessments = [
        item for item in report.get("package_assessments", [])
        if item.get("level") in {"HIGH", "MEDIUM"}
    ]
    if not assessments:
        lines.append("No medium/high capability combinations were recorded.")
    else:
        for item in assessments:
            lines.append(
                f"- `{item['package']}` — {item['level']} ({item['score']}): "
                f"{', '.join(item.get('signals', [])) or 'no named signals'}"
            )

    lines += [
        "",
        "## Telephony",
        "",
        f"- Verification status: {telephony.get('verified', False)}",
        f"- Note: {telephony.get('note', 'No telephony note.')}",
    ]

    lines += ["", "## Hardening", ""]
    lines.extend(f"- {item}" for item in report.get("hardening", []))

    return "\n".join(lines) + "\n"


def html_report(report: dict) -> str:
    data = json.dumps(report, indent=2)
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<title>DroidShield Security Report</title>"
        "<style>body{font-family:system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem}"
        "pre{white-space:pre-wrap;word-break:break-word;background:#f5f5f5;padding:1rem;border-radius:8px}"
        "</style></head><body>"
        "<h1>DroidShield Security Report</h1>"
        "<p>Structured machine-readable evidence is embedded below.</p>"
        f"<pre>{escape(data)}</pre>"
        "</body></html>"
    )
